metadata.format.version = "1.1"

[versions]
minestom = "96543a894f"
zstd = "1.5.5-3"
fastutil = "8.5.12"

nexuspublish = "1.3.0"

[libraries]
minestom = { group = "net.minestom", name = "minestom-snapshots", version.ref = "minestom" }
zstd = { group = "com.github.luben", name = "zstd-jni", version.ref = "zstd" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }

[plugins]
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexuspublish" }
